### PR TITLE
Report burrow's own progress as a fake consumer

### PR DESCRIPTION
**Pull request by timbertson**
While working on https://github.com/linkedin/Burrow/pull/488, I found it difficult to understand where exactly burrow was "up to" in churning through the `__consumer_offsets` backlog.

This PR reports burrow's own progress through this topic as a fake consumer, under the name `"burrow-"+module.name`.

Since there's no actual consumer group, this main downside is that this could be inconsistent between multiple running instances of burrow.

### CODE REVIEW

**Comment by bai** [comment]
Many thanks!

**Comment by gustavosoares** [comment]
@timbertson just wanna clarify something. The lag for this fake consumer should always grow? will it just keep tracking of everything that burrow is processing?

**Comment by timbertson** [comment]
The offset should grow, but the lag should approach ~0 if burrow is keeping
up. The offset just tracks its position in the __conumer_offsets topic.

**Comment by voiprodrigo** [comment]
Hi. I just upgraded to v1.3.1, and noticed these burrow-* consumer groups turning up Grafana.
I'm not sure I follow the purpose of these fake consumers. The lag on them definitely does not approach 0, it's in the millions and the value seems static. But everything else seems fine. 
Is it safe to blacklist these?

**Comment by nkipin-IX** [comment]
We are experiencing the same issue with v1.3.1. The `burrow-{{module.name}}` consumer groups all report the lag on their partitions as equal to the max offset, and live perpetually in STOP status.

**Comment by timbertson** [comment]
We've been running 1.3.0 (where this change first landed) for ages with no
issue, I'll see if anything changes in 1.3.1

**Comment by dimpavloff** [comment]
Same here -- burrow-<consumer> consumer lag continues to increase and the consumer group's status is reported as "ERR" and most of the partitions are in "STOP" status. Seeing this both on 1.3.1 and 1.3.2

**Comment by rbrendler** [comment]
Also seeing this since I upgraded my test stack to the latest binary release (had been running 1.2.2 with a couple 1.3 fixes cherry-picked).  Lag on the fake group is growing and never decreasing, causing lag alerts.

I can add "^burrow-.*" to the blacklist, but this feature appears to be pretty badly broken.  Can we at least allow it to be turned off in configuration?

**Comment by timbertson-zd** [comment]
I'm continuing to investigate this. We run a fork of burrow, my guess is there's a slight bugfix that I failed to port upstream properly (it's a slim diff, so this shouldn't take too long)

**Pull request merged**
