### PR TITLE
Improve zk lock method to avoid trying lock errors

### PR DESCRIPTION
**Pull request by alvarolmedo**
failed to get zk lock on Burrow (#322)
Get fix from https://github.com/Root-App/Burrow/pull/1/files.

### CODE REVIEW

**Comment by alvarolmedo** [comment]
The lint errors aren't releated with the changes of this PR.

**Comment by bai** [comment]
Could you please rebase from master, just pushed a fix for lint error. Not sure how it ended up in master, sorry 🙏

**Comment by bai** [comment]
Thanks. This looks like a legit error, should be fixable with `golangci-lint run --fix`.

**Comment by alvarolmedo** [comment]
@bai lint fixed 
do you plan a new release of burrow soon?

**Comment by bai** [comment]
Many thanks! Will cut a release today.

**Pull request merged**
