### PR TITLE
Annotate partition status with ownership information

### PR DESCRIPTION
**Pull request by marcusking01**
A common issue with a lagging partition(s) is to be able to investigate the machine that is processing those partitions.  With burrow this information isn't readily apparent.  With this patch we are able to query the kafka based ownership information via the sarama's Broker.DescribeGroups API method.  This patch is smart enough to only query for that information if the version of the kafka  brokers support it.  This of course requires that a new configuration variable be added.

### CODE REVIEW

**Comment by toddpalino** [comment]
@marcusking01, please separate out the change to the offset_store (9c6bc74) separately. It's unrelated to the change you're making and needs to be evaluated separately.

**Comment by marcusking01** [comment]
Ok, I've removed that commit

**Comment by marcusking01** [comment]
Ping?  We've been running this for quite some time in production with no issue.

**Comment by BrianGallew** [comment]
+1 on getting this merged.

**Comment by jiminoc** [comment]
+1

**Comment by kai5263499** [comment]
+1

**Comment by toddpalino** [comment]
I'll take a look at this in the rewrite. I wanted to include some functionality like this, and we should be able to by just parsing the offsets topic messages related to the group (which are currently discarded).

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite

**Pull request closed without merging**
