### PR TITLE
Whitelist support

### PR DESCRIPTION
**Pull request by markrileybot**

### CODE REVIEW

**Comment by toddpalino** [comment]
LGTM. Thanks for implementing this!

**Comment by toddpalino** [comment]
Looks like there's a merge conflict. Resolve that, and we can get this added in.

**Comment by jsvisa** [comment]
@markdrago  For the dockerfile, see #105 , you missed the last line

**Comment by markdrago** [comment]
@jsvisa, I think you meant to mention @markrileybot .

**Comment by toddpalino** [comment]
@markrileybot OK, looks like there was a separate PR for that dockerfile fix that I pulled in first. One more merge fix?

**Pull request merged**
