### PR TITLE
fix(slack_notifier): move groupMsgs to local variable

### PR DESCRIPTION
**Pull request by jsvisa**

### CODE REVIEW

**Comment by toddpalino** [comment]
I believe this is going to increase the problem described in #165 and #145, where the notifier will not send messages out if you have specified more than one group in the notifier section. Previously, the slack notifier would try and gather messages until all the groups were bad and then send.

With this, you still have the check to see if you have as many messages as you have groups, but since you're only receiving 1 notification at a time, if you have defined more than 1 group for the slack notifier you will never have a notification sent out.

**Comment by jsvisa** [comment]
@toddpalino Thanks for your advice, I know what's happened. Let's simply it as below:

> If any group in the group is bad, send out the notify out. 

It's that ok?

**Comment by toddpalino** [comment]
I think that's a good plan, provided it also adheres to the interval for the notifier (don't send out a defined notification more often than the interval).

**Comment by toddpalino** [comment]
Note that this problem appears to exist for the email notifier as well as the slack notifier

**Comment by jsvisa** [comment]
@toddpalino This's a good idea. I'll fix it later today.

**Comment by daodennis** [comment]
@jsvisa is the fix already in the pull request that you referenced on Feb. 27th?

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite

**Pull request closed without merging**
