### PR TITLE
Added Docker file for burrow

### PR DESCRIPTION
**Pull request by alexnederlof**
You can now run Burrow from docker. You'd need to overwrite the config with whatever you want, and mount a log folder.

### CODE REVIEW

**Comment by toddpalino** [comment]
This looks like a good idea. Can you add some comments to it to the effect of what's in the PR? Specifically, what you need to modify/do to get burrow to work when you use the Docker file.

**Comment by jgmchan** [comment]
I'm keen to help with this PR as the docker container in Dockerhub is about 3 months old now.

@toddpalino Is there anything specific that you are looking for? The Dockerfile submitted here just builds the Docker image and it can be run by mounting the configuration into the container.

I also have a branch here (https://github.com/linkedin/Burrow/compare/master...jgmchan:dockerfile?expand=1) which does the same thing but builds it on the `alpine` image which makes it much smaller but I'm happy to help on either.

**Comment by alexnederlof** [comment]
I forgot about this PR because we have it in our private repo now. If you want to take over, using the Alpine base image, that is great

**Comment by dbuschman7** [comment]
@jgmchan @alexnederlof @toddpalino
I have done my own variant of a Dockerfile and can provide my implementation as a starting point on another PR. Then we can disucss more. Me version started the the Docker file here and I expanded it a bit.

**Comment by toddpalino** [comment]
@jgmchan The only real thing I was looking for was a little bit of commenting or documentation as to exactly what needs to be changed in the Dockerfile for someone to make it work. Nothing significant, just a note or two with "change this value to X as appropriate for A, B, and C".

**Comment by jgmchan** [comment]
@toddpalino Ok, no problem. Do you want this in the README or just as a comment in the Dockerfile? I think I would prefer the README.

**Comment by toddpalino** [comment]
If you don't think a comment in the Dockerfile is the way to go, you can add a wiki page with a link from the README

**Comment by toddpalino** [comment]
Closing this out in favor of PR #74

**Pull request closed without merging**
