### PR TITLE
Take proxy settings from environment variables

### LINKED ISSUE #55: HTTP_PROXY env variable not respected
By default, `http.Client` reads any available `HTTP_PROXY` or `HTTPS_PROXY` environment variable, and automatically configures itself to use that proxy for outbound requests. This occurs on the `Transport` object. Background available in the [Golang docs](https://golang.org/pkg/net/http/). See the following for some discussion: http://stackoverflow.com/questions/14661511/setting-up-proxy-for-http-client

However, in Burrow's HTTP notifier, the default `Transport` object is overridden to allow for a custom keep-alive setting: https://github.com/linkedin/Burrow/blob/master/http_notifier.go#L94

In practice, this has the effect of ignoring any present `HTTP_PROXY` or `HTTPS_PROXY` env vars, which in turn breaks the HTTP notifier for environments that require proxy access.

POST requests, and presumably also DELETE requests, instead hang with messages like:
`1458928341523479731 [Error] Failed to send POST for group foo in cluster bar at severity ERR (Id 1234-some-uuid): Post https://example.com: net/http: request canceled while waiting for connection`.

### PR DESCRIPTION
**Pull request by nicknovitski**
Resolves #55.

### CODE REVIEW

**Comment by devmage** [comment]
We're testing this on our side right now.

**Comment by devmage** [comment]
Seems to resolve the issue in #55!

**Comment by devmage** [comment]
For reference, this is how the default `Client` configures its `Transport`, seen in https://golang.org/pkg/net/http/#Client

The `DefaultTransport` referenced is found in the definition for `RoundTripper`, seen in https://golang.org/pkg/net/http/#RoundTripper


```go
var DefaultTransport RoundTripper = &Transport{
        Proxy: ProxyFromEnvironment,
        Dial: (&net.Dialer{
                Timeout:   30 * time.Second,
                KeepAlive: 30 * time.Second,
        }).Dial,
        TLSHandshakeTimeout:   10 * time.Second,
        ExpectContinueTimeout: 1 * time.Second,
}
```

**Comment by devmage** [comment]
Thanks @toddpalino !

**Comment by toddpalino** [comment]
Thank you for catching it and providing a quick fix!

**Pull request merged**
