### PR TITLE
Refactor Slack Notifier

### PR DESCRIPTION
**Pull request by niels-s**
The Bearer token was a legacy approach to send 
messages to Slack. Refactor it so we now use private
urls, see https://my.slack.com/services/new/incoming-webhook/

Also changed the way the message is structured by
just use a template instead. It’s more flexible 
I’ve added some example template to the config file.

cc @toddpalino @daodennis

### CODE REVIEW

**Comment by niels-s** [comment]
Fyi the template looks like this: 
screen shot 2017-11-15 at 10 57 04

**Comment by toddpalino** [comment]
The bearer token does not appear to be legacy, according to Slack's documentation: https://api.slack.com/web. That said, I have no problem if we prefer the webhook, but that introduces a different issue.

At this point, I see little difference between the slack notifier and the http notifier. Given that, if this is the preferred method for sending messages to slack, I see no reason to maintain the slack notifier as separate, and instead to just document how to specify the URL and template for a slack message.

**Comment by niels-s** [comment]
@toddpalino I agree there isn't any difference when we start using the Slack Webhook. So I'm fine with removing the slack notifier and just providing some documentation to set things up.

ps: think this should explain bearer tokens are deprecated: https://api.slack.com/custom-integrations/legacy-tokens

**Comment by niels-s** [comment]
Closing since we discussed there wouldn't be any need to have a specific slack notifier, but we can use the http notifier instead

**Pull request closed without merging**
