### PR TITLE
Upgrade sarama to support Kafka 2.0.0 (#440)

### PR DESCRIPTION
**Pull request by haeuserd**
* Upgrade Shopify/sarama to 1.18.0

### CODE REVIEW

**Comment by gabrielfsousa** [comment]
i need this :)

**Comment by sam-obeid** [comment]
+1

**Comment by sfrooster** [comment]
I've rebuilt our burrow install using haeuserd:kafka-2.0 and everything seems to be working again.  Would very much prefer to migrate back to this repo once this is merged (no offense @haeuserd !!! :-) )

**Comment by vvuibert** [comment]
sarama 1.19 is available

**Comment by toddpalino** [comment]
@bai can you jump in here and take a look at this one?

**Comment by bai** [comment]
> @bai can you jump in here and take a look at this one?

Yep this is on my plate; this change has been tested already so LGTM.

**Pull request merged**
