### PR TITLE
Don't need to vendor burrow package itself

### PR DESCRIPTION
**Pull request by niels-s**
When setting up the project locally I notice the burrow package itself was included in the dependency file, which to me makes no sense. Maybe I'm mistaken but I don't see the need for it.

For the tests to pass I needed to update the import statements so burrow is import in lowercase right now.

cc @toddpalino 

```
➜  burrow git:(remove_self_dependency) ✗ go test ./...
ok  	github.com/linkedin/burrow	0.011s
?   	github.com/linkedin/burrow/core	[no test files]
ok  	github.com/linkedin/burrow/core/internal/cluster	0.128s
ok  	github.com/linkedin/burrow/core/internal/consumer	0.034s
ok  	github.com/linkedin/burrow/core/internal/evaluator	2.243s
ok  	github.com/linkedin/burrow/core/internal/helpers	2.321s
ok  	github.com/linkedin/burrow/core/internal/httpserver	0.232s
ok  	github.com/linkedin/burrow/core/internal/notifier	2.573s
ok  	github.com/linkedin/burrow/core/internal/storage	0.316s
ok  	github.com/linkedin/burrow/core/internal/zookeeper	0.117s
?   	github.com/linkedin/burrow/core/protocol	[no test files]
go test ./...  20.14s user 3.39s system 360% cpu 6.525 total
```

### CODE REVIEW

**Comment by toddpalino** [comment]
The uppercase/lowercase is specific to your checkout. The repository is uppercase `Burrow`, and so all the imports should have that as well. For whatever reason, you have it checked out as lowercase `burrow`.

**Comment by niels-s** [comment]
I think burrow is the first golang project I encounter having an uppercase in it's name 😛 
But besides the uppercase "issue", I still think removing Burrow from dependency list is a good thing, don't you?

**Comment by toddpalino** [comment]
Yeah. I had meant to do a clean build somewhere and make sure that it works fine (we'll be getting CI enabled shortly). It was probably just an oversight in creating the deps in the first place.

**Comment by toddpalino** [comment]
In theory, if you were to adjust this PR to have just the change to the Gopkg toml and lock files, it will build against Travis CI now so it will test it for me.

**Comment by toddpalino** [comment]
Fixed this up myself in #294. Thanks for the fix!

**Pull request closed without merging**
