### PR TITLE
Make inmemory module request channel's size configurable

### PR DESCRIPTION
**Pull request by toddpalino**
We ran into a performance problem where offsets that were read (from any source) were being dropped occasionally on the way to the storage module. The only place this can happen without a debug log being generated is in the `helpers.TimeoutSendStorageRequest` call, where if it takes longer than 1 second to send the storage request on the channel, it will be silently dropped.

It turns out that some sufficiently large consumer groups were causing the storage module to take longer than 1 second to return a response at times. This is a separate performance issue that should be addressed (and may be more about us running too many busy clusters through one instance), but the result is that we were hitting the timeout. I tested with extending the timeout to 5 seconds and the problem went away. However, I'm not sure I like this approach (and making that value configurable is a little more work).

Instead, I added a config to the `inmemory` module that allows the size of its request channels, both for itself and the internal ones used for workers, to be configured. The default value is 1, which is the current behavior where every request will block. However, increasing the size of this queue can allow a busy instance of Burrow to weather a delay in request handling internally. I've tested with a value of 10000 and that also resolves our problem (a lower value may work as well), and does not have significant side effects.

### CODE REVIEW

**Comment by daodennis** [comment]
How can I tell if I need to tune this value or if I'm presently dropping offsets?

**Comment by daodennis** [comment]
Also, how does the size of a consumer group actually affect performance of Burrow? Are these zk or  kf offset commits?

**Comment by toddpalino** [comment]
It's really a matter of how long it takes for the storage module to assemble the reply that contains all of the consumer group's offset data. The type of offset doesn't matter.

**Comment by daodennis** [comment]
Ok, when I was storing 3600 offsets it seemed to be pretty speedy.

**Comment by toddpalino** [comment]
Yeah. We're still probably 2 orders of magnitude over that for our largest consumers (15 offsets x 150k partitions, + 10 broker offsets

**Pull request merged**
