### PR TITLE
Add SASL-SCRAM ability to Kafka connection

### PR DESCRIPTION
**Pull request by rjh-yext**
This PR adds the ability to connect to Kafka via SASL-SCRAM 256 or 512

It adds an entry in the SASL Profile configuration called
key=mechanism
value type=string
required=no
default value=(empty)
Which accepts either values SCRAM-SHA-256, SCRAM-SHA-512

Partially addresses #526

### CODE REVIEW

**Comment by bai** [comment]
Thanks for contributing. Could you please rebase your PR off of master and run `make fmt` to fix indentation bits?

**Comment by johnarok** [comment]
This patch worked for my setup, SCRAM + SASL + TLS, thank you @rjh-yext

**Comment by jaapterwoerds** [comment]
Thanks for your work on this PR @rjh-yext. Are you planning to make it ready to be merged into master or can somebody help you with that?

**Comment by jaapterwoerds** [comment]
I could provide a path to fix the linting and merge conflicts, but I'm not sure how to go about that

**Comment by bai** [comment]
Thanks for contributing! Shipped with https://github.com/linkedin/Burrow/pull/627.

**Pull request merged**
